### ISSUE TITLE
Bug: Game crashes

### ISSUE THREAD

**Issue by KELETU66666** [The-Aether-Team/The-Aether-Genesis#139]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

45.0.50

### The Aether Genesis Version

newest

### Is This Bug a Conflict With Another Mod?

no

### Crash Report (if applicable)

---- Minecraft Crash Report ---- // Hi. I'm Minecraft, and I'm a crashaholic.  Time: 2023-05-27 14:15:44 Description: Exception ticking world  java.lang.IllegalAccessError: failed to access class com.aetherteam.aether.entity.monster.Zephyr$RandomFlyGoal from class com.aetherteam.aether_genesis.entity.monster.Tempest (com.aetherteam.aether.entity.monster.Zephyr$RandomFlyGoal is in module aether@1.19.4-1.0.0-beta.3-forge of loader 'TRANSFORMER' @4ed5a1b0; com.aetherteam.aether_genesis.entity.monster.Tempest is in module aether_genesis@1.19.4-0.0.1-forge of loader 'TRANSFORMER' @4ed5a1b0) 	at com.aetherteam.aether_genesis.entity.monster.Tempest.m_8099_(Tempest.java:41) ~[aether_genesis-1.19.4-0.0.1-forge.jar%23162!/:1.19.4-0.0.1-forge] {re:classloading} 	at net.minecraft.world.entity.Mob.<init>(Mob.java:136) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:EntityMixin,pl:mixin:A} 	at net.minecraft.world.entity.FlyingMob.<init>(FlyingMob.java:10) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading} 	at com.aetherteam.aether.entity.monster.Zephyr.<init>(Zephyr.java:38) ~[aether-1.19.4-1.0.0-beta.3-forge.jar%23161!/:1.19.4-1.0.0-beta.3-forge] {re:classloading} 	at com.aetherteam.aether_genesis.entity.monster.Tempest.<init>(Tempest.java:34) ~[aether_genesis-1.19.4-0.0.1-forge.jar%23162!/:1.19.4-0.0.1-forge] {re:classloading} 	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:fml:forge:forge_method_redirector,re:mixin,xf:fml:forge:forge_method_redirector} 	at net.minecraft.world.level.NaturalSpawner.m_46988_(NaturalSpawner.java:231) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:fml:forge:forge_method_redirector} 	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:169) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:fml:forge:forge_method_redirector} 	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:118) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:fml:forge:forge_method_redirector} 	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:108) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:fml:forge:forge_method_redirector} 	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:357) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:311) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:287) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Server thread Stacktrace: 	at com.aetherteam.aether_genesis.entity.monster.Tempest.m_8099_(Tempest.java:41) ~[aether_genesis-1.19.4-0.0.1-forge.jar%23162!/:1.19.4-0.0.1-forge] {re:classloading} 	at net.minecraft.world.entity.Mob.<init>(Mob.java:136) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:EntityMixin,pl:mixin:A} 	at net.minecraft.world.entity.FlyingMob.<init>(FlyingMob.java:10) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading} 	at com.aetherteam.aether.entity.monster.Zephyr.<init>(Zephyr.java:38) ~[aether-1.19.4-1.0.0-beta.3-forge.jar%23161!/:1.19.4-1.0.0-beta.3-forge] {re:classloading} 	at com.aetherteam.aether_genesis.entity.monster.Tempest.<init>(Tempest.java:34) ~[aether_genesis-1.19.4-0.0.1-forge.jar%23162!/:1.19.4-0.0.1-forge] {re:classloading} 	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:fml:forge:forge_method_redirector,re:mixin,xf:fml:forge:forge_method_redirector} 	at net.minecraft.world.level.NaturalSpawner.m_46988_(NaturalSpawner.java:231) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:fml:forge:forge_method_redirector} 	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:169) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:fml:forge:forge_method_redirector} 	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:118) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:fml:forge:forge_method_redirector} 	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:108) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:fml:forge:forge_method_redirector} 	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:357) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:311) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:287) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:A} -- Affected level -- Details: 	All players: 1 total; [ServerPlayer['keletu'/220, l='ServerLevel[新的世界]', x=1030.98, y=84.00, z=628.05]] 	Chunk stats: 2025 	Level dimension: aether:the_aether 	Derived: true 	Level spawn location: World: (16,93,-48), Section: (at 0,13,0 in 1,5,-3; chunk contains blocks 16,0,-48 to 31,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1) 	Level time: 155796 game time, 96962 day time 	Level name: 新的世界 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true 	Level weather: Rain time: 9358 (now: false), thunder time: 132137 (now: false) 	Known server brands: forge 	Level was modded: true 	Level storage version: 0x04ABD - Anvil Stacktrace: 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}   -- System Details -- Details: 	Minecraft Version: 1.19.4 	Minecraft Version ID: 1.19.4 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.7, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation 	Memory: 381419440 bytes (363 MiB) / 2409627648 bytes (2298 MiB) up to 4294967296 bytes (4096 MiB) 	CPUs: 12 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz 	Identifier: Intel64 Family 6 Model 165 Stepping 2 	Microarchitecture: unknown 	Frequency (GHz): 2.59 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: NVIDIA GeForce RTX 2060 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x1f15 	Graphics card #0 versionInfo: DriverVersion=30.0.15.1169 	Graphics card #1 name: Intel(R) UHD Graphics 	Graphics card #1 vendor: Intel Corporation (0x8086) 	Graphics card #1 VRAM (MB): 1024.00 	Graphics card #1 deviceId: 0x9bc4 	Graphics card #1 versionInfo: DriverVersion=27.20.100.9664 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 36895.56 	Virtual memory used (MB): 29755.73 	Swap memory total (MB): 20749.87 	Swap memory used (MB): 6912.50 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx4096m 	Server Running: true 	Player Count: 1 / 8; [ServerPlayer['keletu'/220, l='ServerLevel[新的世界]', x=1030.98, y=84.00, z=628.05]] 	Data Packs: vanilla, mod:aether_genesis, mod:forge, mod:curios (incompatible), mod:twilightforest, mod:aether, mod:continuumation, mod:jei (incompatible), mod:moonlight (incompatible), mod:dummmmmmy (incompatible), mod:structure_gel, mod:lost_aether_content 	Enabled Feature Flags: minecraft:vanilla 	World Generation: Experimental 	Type: Integrated Server (map_client.txt) 	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge' 	Launched Version: 1.19.4-Forge_45.0.50 	ModLauncher: 10.0.8+10.0.8+main.0ef7e830 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.3.jar eventbus PLUGINSERVICE  		fmlloader-1.19.4-45.0.50.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.19.4-45.0.50.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.19.4-45.0.50.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.19.4-45.0.50.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.19.4-45.0.50.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		aether_genesis-1.19.4-0.0.1-forge.jar             |The Aether: Genesis           |aether_genesis                |1.19.4-0.0.1-forge  |DONE      |Manifest: NOSIGNATURE 		moonlight-1.19.4-2.4.3-forge.jar                  |Moonlight Library             |moonlight                     |1.19.4-2.4.3        |DONE      |Manifest: NOSIGNATURE 		forge-1.19.4-45.0.50-universal.jar                |Forge                         |forge                         |45.0.50             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 		dummmmmmy-1.19.4-1.7.8.jar                        |MmmMmmMmmmmm                  |dummmmmmy                     |1.19.4-1.7.8        |DONE      |Manifest: NOSIGNATURE 		curios-forge-1.19.4-5.1.5.1.jar                   |Curios API                    |curios                        |1.19.4-5.1.5.1      |DONE      |Manifest: NOSIGNATURE 		twilightforest-1.19.4-4.2.1681-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1681            |DONE      |Manifest: NOSIGNATURE 		structure_gel-1.19.4-2.12.0.jar                   |Structure Gel API             |structure_gel                 |2.12.0              |DONE      |Manifest: NOSIGNATURE 		aether-1.19.4-1.0.0-beta.3-forge.jar              |The Aether                    |aether                        |1.19.4-1.0.0-beta.3-|DONE      |Manifest: NOSIGNATURE 		lost_aether_content-1.19.4-1.1.3.jar              |Aether: Lost Content          |lost_aether_content           |1.1.3               |DONE      |Manifest: NOSIGNATURE 		Continuumation-1.19.4-1.0.0.jar                   |Continuumation                |continuumation                |1.19.4-1.0.0        |DONE      |Manifest: NOSIGNATURE 		jei-1.19.4-forge-13.1.0.9.jar                     |Just Enough Items             |jei                           |13.1.0.9            |DONE      |Manifest: NOSIGNATURE 	Crash Report UUID: 3d9ae481-471c-4298-8638-c51dba12fc3f 	FML: 45.0 	Forge: net.minecraftforge:45.0.50

### Steps to Reproduce

i don't know, just random tick crashes.

### What You Expect To Happen

game crashes.

### What Actually Happened

game crashes.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [x] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by KELETU66666** [comment]
hmmm, fixed in https://github.com/The-Aether-Team/The-Aether-Genesis/pull/133/commits/f41009c2518142886d279c8338c6a704a3dd7bc7
